#!/usr/bin/env bash

source ~/.git-commands > /dev/null 2>&1

usage() {
    echo "usage: git jira <subcommand>"
    echo
    echo "Available subcommands are:"
    echo -e "take <issue-id>   Grab issue from jira and creates a new branch"
    echo -e "help              Show this help"
}

main() {
    if [ "$#" -lt 1 ]; then
        usage; exit 1
    fi
    
    local subcommand="$1"; shift

    case $subcommand in
        "help")
            usage; exit 0
            ;;
    esac

    export WORKINGDIR=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")
    if [ ! -e "$WORKINGDIR/git-jira-$subcommand" ]; then
        usage; exit 1
    fi

    source "$WORKINGDIR/git-jira-$subcommand"
    source "$WORKINGDIR/jira-helpers"

    type "cmd_$subcommand" > /dev/null

    if [ ! $? ]; then
        usage; exit 1
    fi

    cmd_$subcommand "$@"
}

main "$@"
